// Generated by gencpp from file teng_arduino/channel.msg
// DO NOT EDIT!


#ifndef TENG_ARDUINO_MESSAGE_CHANNEL_H
#define TENG_ARDUINO_MESSAGE_CHANNEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teng_arduino
{
template <class ContainerAllocator>
struct channel_
{
  typedef channel_<ContainerAllocator> Type;

  channel_()
    : stamp()
    , c(0.0)  {
    }
  channel_(const ContainerAllocator& _alloc)
    : stamp()
    , c(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::teng_arduino::channel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teng_arduino::channel_<ContainerAllocator> const> ConstPtr;

}; // struct channel_

typedef ::teng_arduino::channel_<std::allocator<void> > channel;

typedef boost::shared_ptr< ::teng_arduino::channel > channelPtr;
typedef boost::shared_ptr< ::teng_arduino::channel const> channelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teng_arduino::channel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teng_arduino::channel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teng_arduino::channel_<ContainerAllocator1> & lhs, const ::teng_arduino::channel_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teng_arduino::channel_<ContainerAllocator1> & lhs, const ::teng_arduino::channel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teng_arduino

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teng_arduino::channel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teng_arduino::channel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teng_arduino::channel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teng_arduino::channel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teng_arduino::channel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teng_arduino::channel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teng_arduino::channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a18997610954b0a6cd4a6ffda94b3bf";
  }

  static const char* value(const ::teng_arduino::channel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a18997610954b0aULL;
  static const uint64_t static_value2 = 0x6cd4a6ffda94b3bfULL;
};

template<class ContainerAllocator>
struct DataType< ::teng_arduino::channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teng_arduino/channel";
  }

  static const char* value(const ::teng_arduino::channel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teng_arduino::channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float32 c\n"
;
  }

  static const char* value(const ::teng_arduino::channel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teng_arduino::channel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct channel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teng_arduino::channel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teng_arduino::channel_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENG_ARDUINO_MESSAGE_CHANNEL_H
